/**
 * MenuResolver — turn our taco-domain slugs into the real commande.app
 * CUIDs that `order.create` expects.
 *
 * The catch-22 of the migration: every consumer in apps/api works with a
 * stable vocabulary (`TacoSize.L`, option slugs like `viande_hachee_boeuf`,
 * product slugs like `coca_cola_33cl`), but commande.app's `order.create`
 * needs real opaque CUIDs generated by its catalogue. This class fetches
 * the catalogue once per submit and provides lookups by name/slug.
 */

import type { OptionGroup, Product } from '@tacocrew/commande-client';
import { classifyOptionGroup, classifyProductCategory, classifyTacoSize } from '@/domain/taco-config';
import { ValidationError } from '@/shared/utils/errors.utils';

export type OptionKind = 'meat' | 'sauce' | 'garniture';
export type ProductCategory = 'extra' | 'drink' | 'dessert';

export type ResolvedOption = {
  readonly group: OptionGroup;
  readonly groupId: string;
  readonly groupName: string;
  readonly optionId: string;
};

function slugify(name: string): string {
  return name
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

export class MenuResolver {
  private readonly productsById: ReadonlyMap<string, Product>;
  /** TacoSize → product id. Only taco-sized products. */
  private readonly tacoProductIdBySize: ReadonlyMap<string, string>;
  /** category → (slug → product id). */
  private readonly categoryBySlug: ReadonlyMap<ProductCategory, ReadonlyMap<string, string>>;

  constructor(products: readonly Product[]) {
    const byId = new Map<string, Product>();
    const tacoIdBySize = new Map<string, string>();
    const extras = new Map<string, string>();
    const drinks = new Map<string, string>();
    const desserts = new Map<string, string>();

    for (const product of products) {
      byId.set(product.id, product);

      const size = classifyTacoSize(product.name);
      if (size !== undefined) {
        // Prefer the first product we see per size; commande.app sometimes
        // lists duplicates (out-of-stock variants). A stable pick is enough.
        if (!tacoIdBySize.has(size)) tacoIdBySize.set(size, product.id);
        continue;
      }

      const slug = slugify(product.name);
      if (slug === '') continue;
      const category = classifyProductCategory(product.name);
      if (category === 'extra' && !extras.has(slug)) extras.set(slug, product.id);
      else if (category === 'drink' && !drinks.has(slug)) drinks.set(slug, product.id);
      else if (category === 'dessert' && !desserts.has(slug)) desserts.set(slug, product.id);
    }

    this.productsById = byId;
    this.tacoProductIdBySize = tacoIdBySize;
    this.categoryBySlug = new Map<ProductCategory, ReadonlyMap<string, string>>([
      ['extra', extras],
      ['drink', drinks],
      ['dessert', desserts],
    ]);
  }

  /** Look up the commande.app product CUID for a given `TacoSize`. */
  resolveTacoProductId(size: string): string {
    return this.resolveTacoProduct(size).id;
  }

  /** Look up the commande.app product (id + name + imageUrl) for a given `TacoSize`. */
  resolveTacoProduct(size: string): {
    readonly id: string;
    readonly name: string;
    readonly imageUrl: string | null;
  } {
    const id = this.tacoProductIdBySize.get(size);
    if (id === undefined) {
      throw new ValidationError({
        reason: 'menu_missing_taco_size',
        size,
        availableSizes: [...this.tacoProductIdBySize.keys()],
      });
    }
    const product = this.productsById.get(id);
    if (!product) {
      throw new ValidationError({ reason: 'menu_missing_taco_product', productId: id });
    }
    return { id, name: product.name, imageUrl: product.imageUrl ?? null };
  }

  /**
   * Given a taco product id and an option slug, find the matching group+option
   * pair (meat / sauce / garniture).
   */
  resolveTacoOption(tacoProductId: string, kind: OptionKind, slug: string): ResolvedOption {
    const product = this.productsById.get(tacoProductId);
    if (!product) {
      throw new ValidationError({ reason: 'menu_missing_taco_product', productId: tacoProductId });
    }
    for (const group of product.optionGroups) {
      const groupKind = classifyOptionGroup(group);
      if (groupKind !== kind) continue;
      for (const option of group.options) {
        if (slugify(option.name) === slug) {
          return {
            group,
            groupId: group.id,
            groupName: group.name,
            optionId: option.id,
          };
        }
      }
    }
    throw new ValidationError({
      reason: 'menu_missing_option',
      kind,
      slug,
      productId: tacoProductId,
    });
  }

  /** Look up a non-taco product (extra / drink / dessert) by slug. */
  resolveCategoryProductId(category: ProductCategory, slug: string): string {
    const bucket = this.categoryBySlug.get(category);
    const id = bucket?.get(slug);
    if (id === undefined) {
      throw new ValidationError({
        reason: 'menu_missing_product',
        category,
        slug,
      });
    }
    return id;
  }
}
