export const SWITZERLAND_COUNTRY = 'Switzerland';

export const SWISS_CANTONS: Array<{ code: string; label: string }> = [
  { code: 'AG', label: 'Aargau' },
  { code: 'AI', label: 'Appenzell Innerrhoden' },
  { code: 'AR', label: 'Appenzell Ausserrhoden' },
  { code: 'BE', label: 'Bern' },
  { code: 'BL', label: 'Basel-Landschaft' },
  { code: 'BS', label: 'Basel-Stadt' },
  { code: 'FR', label: 'Fribourg' },
  { code: 'GE', label: 'Genève' },
  { code: 'GL', label: 'Glarus' },
  { code: 'GR', label: 'Graubünden' },
  { code: 'JU', label: 'Jura' },
  { code: 'LU', label: 'Luzern' },
  { code: 'NE', label: 'Neuchâtel' },
  { code: 'NW', label: 'Nidwalden' },
  { code: 'OW', label: 'Obwalden' },
  { code: 'SG', label: 'St. Gallen' },
  { code: 'SH', label: 'Schaffhausen' },
  { code: 'SO', label: 'Solothurn' },
  { code: 'SZ', label: 'Schwyz' },
  { code: 'TG', label: 'Thurgau' },
  { code: 'TI', label: 'Ticino' },
  { code: 'UR', label: 'Uri' },
  { code: 'VD', label: 'Vaud' },
  { code: 'VS', label: 'Valais' },
  { code: 'ZG', label: 'Zug' },
  { code: 'ZH', label: 'Zürich' },
];
